version: '3'
services:
  crawler:
    container_name: crawler
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - LOG_LEVEL=debug
    command: -d 3 -l 30 https://python-poetry.org/docs
    