version: '3'
services:
  crawler:
    container_name: crawler
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - LOG_LEVEL=info
    volumes:
      - ./data/:/app/data
    command: -d 2 -l 10 https://python-poetry.org/docs
    